### ISSUE TITLE
Problem with Node.js

### ISSUE THREAD

**Issue by matduarte** [pichillilorenzo/JavaScript-Completions#13]
Every time on running of ST, JavaScript-Completions checks Node.js version, this cause ST freezing for 4 - 5 seconds.

**Comment by pichillilorenzo** [comment]
I didn't notice it! Maybe because on my computer it takes only ~1 second
This happens because I handle the loading of some files of the plugin in a certain way!
I will try to solve this! 

Thanks for the support!

**Comment by sofoklesion** [comment]
Hello guys,
I'd like to say Thank you to author of this plugin, great job buddy!
I tried to install plugin in some scenarios (SBT3, portable stable build 3114, Win 7x64):

- with plugins,
- fresh SBT portable (no plugins),
- fresh SBT3 install (no plugins).

Well, there are some issues - I'm not expert on this, so I'll not speculate... you can see my complete log after fresh start, if you are interested.

And once more... Thank you @pichillilorenzo for your hard work!

[log.txt](https://github.com/pichillilorenzo/JavaScript-Completions/files/484716/log.txt)

**Comment by pichillilorenzo** [comment]
@sofoklesion I update it! I was testing it on windows and i was having your same issue. Now it should be ok! Say me if it works! 

Wait until Package Control update my url for this new release!

**Comment by sofoklesion** [comment]
OK buddy, I will come back to you with updated status after proper upgrade from package control.

**Comment by pichillilorenzo** [comment]
Package Control updated it. You can check now!

**Comment by sofoklesion** [comment]
Cool, I'm on it, will be back in couple minutes with result.

**Comment by sofoklesion** [comment]
OK, I did two scenarios:

- upgrade via control package
- clean install (all rest files in SBT3 cleared)

nodejs problem is gone and seems to be fast proces with no impact to user.
But there is some issue with import _init... you can see my fresh log. (This issue is valid for both scenarios)

Thanks @pichillilorenzo 

[log-2016-09-22-0011hod.txt](https://github.com/pichillilorenzo/JavaScript-Completions/files/486145/log-2016-09-22-0011hod.txt)

**Comment by pichillilorenzo** [comment]
The "import _init" issue is a false-positive! This happens, like i said before, because I handle the loading of some files of the plugin in a certain way! So it isn't a real issue :thumbsup:

However i'm going to update this plugin with some other features!

**Comment by sofoklesion** [comment]
Aha... ok, thanks for your work. I'm looking forward to it! Wish you the best... :+1:

**Comment by pichillilorenzo** [comment]
Hey @matduarte! i found the "issue" that cause ST freezing. My plugin has dependencies with some other my python modules. Sublime Text 3 loads plugin in async way, so i must check and, in case, reload these python modules to get plugin work properly!

**Comment by infobeny** [comment]
Hi @pichillilorenzo,
I tried to activate your plugin and could see in SBT3 console:

- `"Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'"`

- Seems path  shoud be: `"\nodejs\node_modules\npm\bin\npm-cli.js"` --> part  **"\node_modules\npm\bin\"** is repeating yourself and of course cannot be found.

- Maybe some troubles with vars definition in __node_variables.py__?

---
ENV: 

- portable SBT3-x64, latest stable build, installed on non-system hdd (D:)
- win 7 x64
- node 6.6.0

**Comment by pichillilorenzo** [comment]
To use npm on windows, you must download and install it on your own from [https://nodejs.org/](https://nodejs.org/)! i can't install locally in automatic way on windows, like I do instead for OSX and Linux, because of some problems about the folder tree depth of npm packages!

In /node/main.py, for windows, i use directly "npm" without the entire path, like I do instead for OSX and Linux,  because of the problem i explained.

So have you installed npm on your system??

However I done a test and I used:
- portable SBT3-x64, latest stable build, installed on USB (D:)
- win 10 x64
- node 6.6.0

and the plugin works properly.

Obviously i have npm installed on the system!

**Comment by pichillilorenzo** [comment]
@infobeny  try this: [http://stackoverflow.com/a/24741740](http://stackoverflow.com/a/24741740)

**Comment by infobeny** [comment]
Good point @pichillilorenzo. I'm using npm every day and no problem. I checked system path and and except `C:\Program Files\nodejs` there was extra path `C:\Program Files\nodejs\node_modules\npm\bin`. When you delete this extra path, there is no problem with your plugin anymore. thx!

**Comment by panczarny** [comment]
Hello,
I've got a similar problem :(
Downloaded the newest NodeJS (v7.0.0), changed in settings to use this version, but every time I start ST3 this happens:
[TL;DW: goto sec 53](http://recordit.co/hHK50GKGso)
![ST3 JS Completions Node problem](http://g.recordit.co/hHK50GKGso.gif)
_it lasts 58 secs, so I recommend to see the url_

**Comment by pichillilorenzo** [comment]
@panczarny What is the problem? i didn't understand! Can you post logs from Sublime Text console please??

**Comment by panczarny** [comment]
This is what the consol says:
`scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/acorn-jsx has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/acorn-jsx-b162829a inode: 76561193665317381
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/bluebird has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/bluebird-78c9a2f9 inode: 15199648742394678
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/acorn has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/acorn-98c00d00 inode: 7036874417785969
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/escape-string-regexp has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/escape-string-regexp-79dba728 inode: 17169973579369303
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/espree has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/espree-650ba9de inode: 60798594969520971
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/catharsis has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/catharsis-56ffe948 inode: 11540474045156158
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/graceful-fs has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/graceful-fs-b04e9bc4 inode: 19421773393054325
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/js2xmlparser has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/js2xmlparser-7a8769c7 inode: 9851624184892259
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/klaw has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/klaw-45eb3118 inode: 10414574138313574
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/jsdoc has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/jsdoc-458e3200 inode: 4222124650679416
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/minimist has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/minimist-1ffe314f inode: 8725724278049518
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/marked has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/marked-b796fea1 inode: 4222124650679413
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/mkdirp has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/mkdirp-cf6d1dab inode: 11540474045156467
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/requizzle has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/requizzle-e5225bd9 inode: 4222124650679248
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/strip-json-comments has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/strip-json-comments-157f2953 inode: 12103423998577518
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/taffydb has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/taffydb-11b2c6e8 inode: 63331869759917002
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/underscore has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/underscore-a0dc02cb inode: 4785074604100691
scan: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/underscore-contrib has been seen before, skipping (using inode) previous path: /C/Users/czarny/AppData/Roaming/Sublime Text 3/Packages/JavaScript Completions/node_modules/.staging/underscore-contrib-cdaa9e50 inode: 7599824371206900
Traceback (most recent call last):
  File "C:\Users\czarny\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node\installer.py", line 117, in checkUpgrade
    if node_js.getCurrentNodeJSVersion() != nodejs_latest_version :
  File "C:\Users\czarny\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node\main.py", line 56, in getCurrentNodeJSVersion
    raise Exception(lines)
Exception: '"C:\Users\czarny\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node_binaries\windows-64bit\node.exe"' is not recognized as an internal or external command,

operable program or batch file.
`

**Comment by panczarny** [comment]
I think this might be an issue:
Traceback (most recent call last):
File "C:\Users\michal\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node\installer.py", line 117, in checkUpgrade if node_js.getCurrentNodeJSVersion() != nodejs_latest_version :
File "C:\Users\michal\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node\main.py", line 56, in getCurrentNodeJSVersion raise Exception(lines)
Exception: '"C:\Users\michal\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\node_binaries\windows-64bit\node.exe"' is not recognized as an internal or external command, operable program or batch file.

But this is weird, because I've got the newest NodeJS version that is available installed...

**Comment by akshayvinchurkar** [comment]
looks like node environment variable is not set

**Comment by tnga** [comment]
most javaScript developers have an experience with nodejs now and have certainly installed it in their computer. 

I think it will better to just install the plugin and let it try to use user's installed nodejs instead of automatically try to install local one. An option can be provided for user who don't have a global nodejs installation, to enable automatic download, update and usage of local one. Another option can be provided to disable automatic npm update.

**Comment by flawiddsouza** [comment]
Hey, any progress on the issue of sublime text freezing for 4-5 seconds on every load?

**Comment by pichillilorenzo** [comment]
@tnga I install nodejs and npm local because of implementation of plugin features, such as JSDoc or "Evaluate JavaScript". 

@flawiddsouza not yet

**Comment by pichillilorenzo** [comment]
The problem is not caused by Node.js but from loading of all the sublime-completions files! I will update it as soon as possible

**Comment by pichillilorenzo** [comment]
@flawiddsouza try the new version about the freezing problem and let me know!

**Comment by flawiddsouza** [comment]
The lag is lesser but it hasn't completely disappeared. 2-3 seconds now :confused:

**Comment by pichillilorenzo** [comment]
Ok @flawiddsouza! I will check it again, but it is strange because i load my sublime completions in an asynchronous way!

**Comment by flawiddsouza** [comment]
Disabling this package removes the lag, so I'm pretty sure the problem is in here somewhere. I'm on a SSD and I still get this. Maybe it's the npm check at startup. Is there anything I give you to help you with this?

**Comment by pichillilorenzo** [comment]
Installing nodejs and/or checking for update with npm is done also in asynchronous way! I will check later if I can solve this! Thanks

**Comment by Paviluf** [comment]
Any news ?
