### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by lannex** [pichillilorenzo/JavaScript-Completions#14]
Hi.

'Auto-complete' it does not work after the update.
(ex. DOM selectors, array functions, etc..)

**Comment by pichillilorenzo** [comment]
I have reinstalled it on my computer and it works!

![schermata 2016-09-22 alle 10 56 12](https://cloud.githubusercontent.com/assets/5956938/18742234/6318f7ac-80b3-11e6-967a-5d6fcb10c123.png)

It gives me hints and completions.

What version of Sublime are you using? what Operative System? Can you give me the logs when you start Sublime Text??

**Comment by lannex** [comment]
![image](https://cloud.githubusercontent.com/assets/7369541/18744357/9b1e5a1c-80f8-11e6-9890-e926b206c965.png)

```
...
reloading plugin JavaScript Completions._created_evaluate_javascript
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\xxxxx\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_created_evaluate_javascript.py", line 4, in <module>
    import _init
ImportError: No module named '_init'
reloading plugin JavaScript Completions._created_helper
...
```

I have been using Sublime3, Windows, ES6 and JSX.
other 'autocomplete' work well.

**Comment by pichillilorenzo** [comment]
This error "import _init" is a false-positive! see comments on #13 

Can you give me the whole logs??

**Comment by pichillilorenzo** [comment]
However I tried this plugin on Windows 10, Sublime Text 3 Build 3124, with also this plugins installed: 

- ES6-Toolkit
- JavaScriptNext - ES6 Syntax
- JSX

and it works properly! I got hints and completions.

Did you try uninstalling and reinstalling this plugin??

**Comment by lannex** [comment]
```
DPI scale: 1
startup, version: 3124 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Shin/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Shin/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Shin/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["CSS", "JavaScript", "Panda Syntax Sublime", "Vintage"]
pre session restore time: 0.4295
startup time: 0.4695
first paint time: 0.4695
first paint time: 0.4705
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.changes
reloading plugin BracketHighlighter.support
reloading plugin Chain of Command.chain
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin Material Theme.mt_activator
reloading plugin Material Theme.mt_changes
reloading plugin Material Theme.mt_config
reloading plugin Material Theme.mt_info
reloading plugin Material Theme.mt_urls
reloading plugin MoveTab.move_tab
reloading plugin npm.cli
reloading plugin npm.command
reloading plugin npm.install
reloading plugin npm.link
reloading plugin npm.list
reloading plugin npm.outdated
reloading plugin npm.rm
reloading plugin npm.run_arbitrary
reloading plugin npm.script
reloading plugin npm.search
reloading plugin npm.settings
reloading plugin npm.test
reloading plugin npm.update
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin RegReplace.rr_edit
reloading plugin RegReplace.rr_notify
reloading plugin RegReplace.rr_plugin
reloading plugin RegReplace.rr_replacer
reloading plugin RegReplace.rr_sequencer
reloading plugin RegReplace.rr_upgrade
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Sublime Files.sublime_files
reloading plugin SublimeLinter-contrib-sass-lint.linter
SublimeLinter: sass linter loaded 
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin Babel.Babel
reloading plugin JavaScript Completions._created_evaluate_javascript
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Shin\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_created_evaluate_javascript.py", line 4, in <module>
    import _init
ImportError: No module named '_init'
reloading plugin JavaScript Completions._created_helper
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Shin\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_created_helper.py", line 3, in <module>
    import util.main as Util
ImportError: No module named 'util'
reloading plugin JavaScript Completions._created_javascript_completions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Shin\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_created_javascript_completions.py", line 4, in <module>
    import _init
ImportError: No module named '_init'
reloading plugin JavaScript Completions._init
reloading plugin JavaScript Completions.reloader
reloading plugin LiveStyle.livestyle-plugin
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
SublimeLinter: debug mode: off 
LiveStyle: Start app
unloading plugin JavaScript Completions._created_evaluate_javascript
unloading plugin JavaScript Completions._created_helper
unloading plugin JavaScript Completions._created_javascript_completions
Emmet: No need to update PyV8
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
reloading plugin JavaScript Completions._created_evaluate_javascript
reloading plugin JavaScript Completions._created_helper
reloading plugin JavaScript Completions._created_javascript_completions
Package Control: Skipping automatic upgrade, last run at 2016-09-23 09:11:54, next run at 2016-09-23 10:11:54 or after

```

Yes. twice reinstalling this plugin.
It works well when i turn on jQuery or Native javascript option. (just options.)
But still it does not work is the basic things.

**Comment by pichillilorenzo** [comment]
So, if you turn on jQuery for example, you get also completions of DOM, arrays, etc??

Try this: use default settings and check logs after typing something in a javascript context (like "document", "getElement ... ", etc)! Maybe there are problems with some completions during query completions.

or maybe did you set User's settings??

**Comment by lannex** [comment]
Um,...
Strange point, it is work well with Mac. (User's setting is both Windows and Mac share.)

Maybe it is my system problem.

I will try again to reinstall the 'Sublime Text3'.

**Comment by pichillilorenzo** [comment]
Ok.. If the problem persists, try like I said and show me your logs!

**Comment by Henerator** [comment]
I had the same problem. Not working auto-completion of words. Reinstallation did not help. The problem was solved by disabling - enabling the plugin on every startup. Then I opened the plugins folder and found several folders JavaScriptCompletions, deleted all, installed again. Still works without problems.

**Comment by pichillilorenzo** [comment]
Thank you @Henerator! 
So, maybe, is a bug of Sublime Text itself?
What is the exact version of Sublime Text you are using? What Build?

**Comment by Henerator** [comment]
Sublime Text 3. Now it is 3124Build, but the problem had appeared after upgrading from the previous build.

**Comment by pichillilorenzo** [comment]
Ok! I don't know why you found several folders "JavaScript Completions" into plugins folder!
