### ISSUE TITLE
i click to see full screen api on can i use function and this is happend

### ISSUE THREAD

**Issue by akshayvinchurkar** [pichillilorenzo/JavaScript-Completions#16]
![this](https://cloud.githubusercontent.com/assets/10510889/18943144/5dad46dc-863b-11e6-861a-42f9969fe1c1.jpg)

i don't know what is wrong here it just flip

**Comment by pichillilorenzo** [comment]
I tested it, with different resolutions, on OSX and Windows 10 but i can't reproduce this bug! it is strange, i don't know why it is happening!

This happen only with Full Screen API ?  or also with all items of the list??

Could be maybe some settings about the font that you use on sublime text?

**Comment by akshayvinchurkar** [comment]
its default font its happened everywhere not just full screen api

**Comment by pichillilorenzo** [comment]
Strange.. I simply concatenate strings with html and in some case i use also ```cgi.escape("string")``` to escape some characters! However, even if a want to do something like that, I could not do it! 

Sublime Text provides [minihtml](https://www.sublimetext.com/docs/3/minihtml.html), only a limited subset of HTML and CSS features, and i can't do something like you posted! Maybe could be a bug of Sublime Text itself??

Could you post also an image with the whole content of the popup?

**Comment by akshayvinchurkar** [comment]
How?

**Comment by pichillilorenzo** [comment]
Do a first screenshot, then scroll the popup and do another screenshot

**Comment by pichillilorenzo** [comment]
Could you post also logs that comes from Sublime Text console??

**Comment by akshayvinchurkar** [comment]
File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\Designer\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-au3check.sublime-package", line 13, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter-phplint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\Designer\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-phplint.sublime-package", line 13, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin WordPress Developer Resources.SublimeWPDeveloperResources
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JavaScript Completions._generated_2016_09_26_at_21_37_12
reloading plugin JavaScript Completions.reloader
reloading plugin SublimeTextTrans.SublimeTrans
plugins loaded
Notice: Load/Reload settings incase user modified
Initializing 1self plugin
Emmet: No need to update PyV8
reloading settings Packages/User/Fetch.sublime-settings
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
Package Control: No updated packages
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
reloading settings Packages/User/SublimeTextTrans.sublime-settings
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources

**Comment by akshayvinchurkar** [comment]
this is kind of log

**Comment by akshayvinchurkar** [comment]
![1](https://cloud.githubusercontent.com/assets/10510889/18951263/ea722166-8661-11e6-923f-59feb8d924ad.jpg)
![2](https://cloud.githubusercontent.com/assets/10510889/18951264/ea838d98-8661-11e6-948b-f71f7d41b551.jpg)

**Comment by pichillilorenzo** [comment]
Ok, there aren't errors about my plugin.. I don't know why it is happening! It is very strange..
You could try to uninstall some other plugin and see if maybe there is a plugin that cause this to mine!

I see a lot of warnings about:
```
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
```

**Comment by akshayvinchurkar** [comment]
ok i try to debug if i find solution i will share with you and thank you for your time

**Comment by pichillilorenzo** [comment]
Thanks to you for the support!

**Comment by danekszy** [comment]
This looks like an issue with text direction... Seems like the view is rendered RTL. 🤔

**Comment by pichillilorenzo** [comment]
@akshayvinchurkar do you have some news about that?? Thanks!
