### ISSUE TITLE
Custom Completions not working

### ISSUE THREAD

**Issue by panczarny** [pichillilorenzo/JavaScript-Completions#18]
Hello,
I had created my .sublime-completions file and since I've installed the JavaScript Completions my custom completions don't execute.
When I'm ignoring JavaScript Completions my completions work again.
How we can manage this to work simultaneously?

This is my .sublime-completions file:
`
{

```
"scope": "source.js",
"completions": [
    { "trigger": "_function with name (MY)", "contents": "function ${1:function_name}(${2:argument}) {\n\t${0:/*body...*/}\n}${3:;}" },
    { "trigger": "_function without name (MY)", "contents": "function(${1:argument}) {\n\t${0:/*body...*/}\n}${2:;}" },
    { "trigger": "for (MY)", "contents": "for(${2:i} = ${1:Things}.length - 1; ${2:i} >= 0; ${2:i}--){\n\t${3:${1:Things}[${2:i}]}${0}\n}" }
]
```

}
`

**Comment by pichillilorenzo** [comment]
I checked it and I discovered that when I load my completions, if there is a space in "trigger" or "contents" field in one of them, .sublime-completions files don't want load! I don't know why.. Maybe it is a Sublime Text's bug! However you can try to write your custom completions like snippets! 

To write a snippet, go to: Tools -> Developer -> New Snippet... 
Docs: [http://docs.sublimetext.info/en/latest/extensibility/snippets.html](http://docs.sublimetext.info/en/latest/extensibility/snippets.html)

Your custom snippets should works now!

**Comment by panczarny** [comment]
Huh,
truly it was caused by spaces. Without them my custom completions work like a charm!
Thanks a lot!

**Comment by cheoAlejo** [comment]
Hi @panczarny , how you managed to fix your completions ? My custom completions don't work either.
Could you give me an example of the fix ?
Here's an example of a simple completion that doesn't work when **Javascript Completions** is enabled:

```json
{
    "scope": "source.js - string.quoted",


    "completions":
    [
        { "trigger": "mostrar_capa_general", "contents": "mostrar_capa_general" }
    ]
}
```

**Comment by panczarny** [comment]
Hello, your example works in my ST3

**Comment by pichillilorenzo** [comment]
Hi @cheoAlejo! Can you post logs from sublime text's console when you start sublime text with my plugin enabled and your completions please? 
However what is the exact version of your sublime text?? Which OS?

**Comment by cheoAlejo** [comment]
My sublime versión: Build 3126
Os: Windows 10

I have my custom javascript completions in this path:
`C:\Users\Sergio\AppData\Roaming\Sublime Text 3\Packages\Eco-Hints\JS\funciones.sublime-completions`

**Console log at startup:**
```
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Sergio/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Sergio/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Sergio/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["ColorPicker", "Markdown", "Vintage"]
Unable to decode Packages/Materialize-Appbar/assets/commons/dirty_icon.png
pre session restore time: 13.0439
startup time: 14.4349
first paint time: 14.4659
first paint time: 14.4659
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AceJump.ace_jump
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin AltUp.run_multiple_commands
reloading plugin Auto Close HTML Tags.auto_close
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorHelper.color_helper
reloading plugin ColorHelper.color_helper_insert
reloading plugin ColorHelper.color_helper_picker
reloading plugin ColorHelper.color_helper_util
reloading plugin ColorHelper.multiconf
reloading plugin ColorHelper.support
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
reloading plugin Expand Selection to Function (JavaScript).expand_selection_to_function_javascript
reloading plugin ExpandRegion.__init__
reloading plugin ExpandRegion.expand_region_handler
reloading plugin ExpandRegion.expand_to_indent
reloading plugin ExpandRegion.expand_to_line
reloading plugin ExpandRegion.expand_to_quotes
reloading plugin ExpandRegion.expand_to_regex_set
reloading plugin ExpandRegion.expand_to_semantic_unit
reloading plugin ExpandRegion.expand_to_subword
reloading plugin ExpandRegion.expand_to_symbols
reloading plugin ExpandRegion.expand_to_word
reloading plugin ExpandRegion.expand_to_word_with_dots
reloading plugin ExpandRegion.expand_to_xml_node
reloading plugin ExpandRegion.ExpandRegion
reloading plugin ExpandRegion.html
reloading plugin ExpandRegion.javascript
reloading plugin ExpandRegion.latex
reloading plugin ExpandRegion.python
reloading plugin ExpandRegion.utils
reloading plugin FAlign.falign
reloading plugin File History.file_history
reloading plugin Function Name Display.FunctionNameStatus
reloading plugin Git.git_commands
reloading plugin GotoDocumentation.goto_documentation
reloading plugin Indent and braces.indent-and-braces
reloading plugin iOpener.i_opener
reloading plugin iOpener.matching
reloading plugin iOpener.paths
reloading plugin JumpTo.jump_to
reloading plugin Log Highlight.Log Highlight
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Material Theme.MT
reloading plugin Modific.Modific
reloading plugin Move By Symbols.move_by_symbols
reloading plugin Move By Symbols.symbols_highlighting
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin QuickLinks.QuickLinks
reloading plugin Schemr.schemr
reloading plugin ScopeHunter.scope_hunter
reloading plugin ScopeHunter.scope_hunter_notify
reloading plugin ScopeHunter.support
reloading plugin SelectExact.select_exact
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin StyleToken.StyleToken
reloading plugin Sublime Bookmarks.bookmark
reloading plugin Sublime Bookmarks.bookmarkWatcher
reloading plugin Sublime Bookmarks.common
reloading plugin Sublime Bookmarks.sublimebookmark
reloading plugin Sublime Bookmarks.ui
reloading plugin Sublime Bookmarks.visibilityHandler
reloading plugin SublimeLinter-contrib-htmlhint.linter
SublimeLinter: htmlhint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin Table of comments.tableofcomments
reloading plugin ToggleQuotes.toggle_quotes
reloading plugin WordCompletion.main
reloading plugin ASCII Decorator.ASCII Decorator
Couldn't load pkg_resources
reloading plugin ASCII Decorator.subcomments
reloading plugin ASCII Decorator.subfiglet
reloading plugin CodeComplice.CodeComplice
reloading plugin ECO.CloneFileIntoNewGroup
reloading plugin ECO.FontPicker
reloading plugin ECO.LineHeightChanger
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JavaScript Completions._generated_2017_03_30_at_17_44_57
reloading plugin JavaScript Completions.reloader
reloading plugin phpfmt.phpfmt
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading settings Packages/User/phpfmt.sublime-settings
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
reloading plugin SublimeLinter-contrib-stylelint.linter
SublimeLinter: stylelint linter loaded 
reloading plugin Terminal.Terminal
plugins loaded
unicode error in opening file 'C:\servidoreco\www\gd\inicio.php'. trying 'latin-1' codec
unicode error in opening file 'C:\servidoreco\www\gd\gd_scripts\variablesinicio.js'. trying 'latin-1' codec
SublimeLinter: cannot find the gutter theme 'Material-Theme', using the default 
SublimeLinter: debug mode: off 
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Sergio\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2017_03_30_at_17_44_57.py", line 781, in donwload_can_i_use_json_data
    os.remove(path_to_test_can_i_use_data)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Sergio\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Completions\\helper\\can_i_use\\can_i_use_data2.json'

C:\Users\Sergio\AppData\Roaming\Sublime Text 3
LOADING BOOKMARKS
```

**Comment by pichillilorenzo** [comment]
Ok @cheoAlejo i will test your completions in Windows 10 to find the problem! However could you try to uninstall and reinstall my plugin please? Let me know if it works after that! Thanks

**Comment by cheoAlejo** [comment]
I uninstalled and reinstalled the package, but the problem continues.

**Comment by pichillilorenzo** [comment]
Ok, I will check it!

**Comment by pichillilorenzo** [comment]
Hi @cheoAlejo! Try the new version and let me know if it now works!
If it doesn't work, try to change the path of your completions like this:

from:
`C:\Users\Sergio\AppData\Roaming\Sublime Text 3\Packages\Eco-Hints\JS\funciones.sublime-completions`

to:
`C:\Users\Sergio\AppData\Roaming\Sublime Text 3\Packages\Eco-Hints\funciones.sublime-completions`

**Comment by cheoAlejo** [comment]
Yes ! they work perfect now. Thanks !
