### ISSUE TITLE
ValueError: Unterminated string starting at: line 1 column 1146878 (char 1146877)

### ISSUE THREAD

**Issue by httpgit** [pichillilorenzo/JavaScript-Completions#19]
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "D:\Program Files\Sublime Text 3\Data\Packages\JavaScript Completions_generated_2016_09_26_at_21_37_12.py", line 756, in donwload_can_i_use_json_data
    json_file = json.load(json_file)
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/**init**.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Unterminated string starting at: line 1 column 1146878 (char 1146877)

**Comment by pichillilorenzo** [comment]
Try the new version and let me know!
Thanks for the support
