### ISSUE TITLE
(Not working) 'Create class from object literal'

### ISSUE THREAD

**Issue by samueltlgg** [pichillilorenzo/JavaScript-Completions#34]
Hi - thanks a lot for this plugin.

I've just installed it and the 'create class from object literal' feature isn't working. Here's what I get in the console output after trying on a valid literal:

`Traceback (most recent call last):
  File "C:\..\Sublime text\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\..\Sublime text\Data\Packages\JavaScript Completions\_generated_2017_03_05_at_21_51_28.py", line 1129, in run
    object_literal = json.loads(node.eval("JSON.stringify("+object_literal+")", "print"))
  File "C:\..\Sublime text\Data\Packages\JavaScript Completions\node\main.py", line 37, in eval
    raise Exception(lines)
Exception: [eval]:1

JSON.stringify({

               ^

SyntaxError: Unexpected end of input

    at createScript (vm.js:53:10)

    at Object.runInThisContext (vm.js:95:10)

    at Object.<anonymous> ([eval]-wrapper:6:22)

    at Module._compile (module.js:571:32)

    at Immediate.<anonymous> (bootstrap_node.js:390:29)

    at runCallback (timers.js:666:20)

    at tryOnImmediate (timers.js:639:5)

    at processImmediate [as _immediateCallback] (timers.js:611:5)
`

**Comment by pichillilorenzo** [comment]
Could you post your object literal that cause this error?

Thanks!

**Comment by samueltlgg** [comment]
Hi Lorenzo,

The object literal I've tried is a copy of the one that is demonstrated with in the gif tutorial on the package control page. So it's:

```
var Person = {
    name: 'required',
    surname: 'required',
    email: '',
    age: 17
}
```

The same error is reported on different (more fields) constructors, too.

**Comment by pichillilorenzo** [comment]
I tried it and it works! 
Maybe it could be something related to the OS! 
I have OSX, but I will check on a PC to see what is going wrong

**Comment by pichillilorenzo** [comment]
Try the new version! Let me know! 
Thanks

**Comment by samueltlgg** [comment]
Hi,

Yes, thank you. It works now. I apologise for not letting you know I was running on Windows 10! Thanks again
